backend:
  name: github
  repo: jaynagpaul/timepass #replace with your username/repo

publish_mode: editorial_workflow
media_folder: src/content/img
display_url: https://timepassmoney.com

collections:
  - name: post
    label: Post
    folder: src/content
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {
          name: author,
          label: Author,
          widget: string,
          hint: 'Use Gary (edit author.yaml to change the author bio)',
        }
      - name: tags
        label: Tags
        widget: list
        hint: 'Comma Seperated (edit tag.yaml to add custom tag info)'
      - { name: image, label: Cover Image, widget: image, allow_multiple: false }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
