backend:
  name: github
  repo: jaynagpaul/timepass #replace with your username/repo

media_folder: src/content/img

collections:
  - name: blog
    label: Blog
    folder: src/content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
